### ISSUE TITLE
Sprite Issue

### ISSUE THREAD

**Issue by ChristofferDL** [Obtaizen/ox_target#1]
Seems like when sprites are too close to each other they bug out. And just spawn somewhere nearby random.

https://github.com/Obtaizen/ox_target/assets/50109212/87d09222-5a51-46f2-9f59-24e21bc1bbbb

**Comment by ChristofferDL** [comment]
Any help with this?

**Comment by Obtaizen** [comment]
I mean it depends what your doing, I see you've got a sign in and out bored but what our the other spirtes for?

**Comment by ChristofferDL** [comment]
So sign in and out, personal locker in the corner. and the one outside is check in, for a hospital. The locker one seems to disappear when the sign in one comes in range.

**Comment by ChristofferDL** [comment]
Got same problem in PD where sprites are close to each other.

**Comment by Obtaizen** [comment]
How close to each other? because I don't have any problems?

**Comment by ChristofferDL** [comment]
See the video, At the end, you can see the sprite on the left disapearing when the one on the right appears.

**Comment by Obtaizen** [comment]
I mean idk. I have no issues like this at at

**Comment by ChristofferDL** [comment]
Strange :/
